# azure-pipelines.yml

trigger:
  - main  # Trigger the pipeline on changes to the main branch

pool:
  vmImage: 'ubuntu-latest'  # Use an Ubuntu virtual machine for the pipeline

steps:
  # Step 1: Install Python
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'  # Specify the Python version
      addToPath: true

  # Step 2: Install dependencies
  - script: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    displayName: 'Install Dependencies'

  # Step 3: Run unit tests
  - script: |
      pytest
    displayName: 'Run Unit Tests'

  # Step 4: Run the application
  - script: |
      python add.py
    displayName: 'Run Application'
